### ISSUE TITLE
Include "protocol" in the headline

### ISSUE THREAD

**Issue by lukasetter** [galaxypi/galaxy.ooo#32]
**Description**
After updating the project description we should include the word protocol in the headline on the home page.

**Suggestion**
"Galaxy is a blockchain agnostic, always on, node network and protocol [_leave away?_ : offering services to other decentralized platforms]"

**Comment by guylepage3** [comment]
Thanks @lukasetter. I’ll update this today.

**Comment by guylepage3** [comment]
Working on this now.
